'use client'

import { useState, useEffect } from 'react'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Alert, AlertDescription } from '@/components/ui/alert'
import { Loader2, CheckCircle, XCircle, Clock, AlertCircle, Eye, FileText } from 'lucide-react'
import { useToast } from '@/hooks/use-toast'
import { createClient } from '@/lib/supabase/client'

interface PaymentAdviceMemo {
  id: string
  leave_plan_request_id: string
  staff_id: string
  staff_name: string
  staff_number: string
  memo_subject: string
  memo_body: any
  hr_leave_office_id: string
  hr_leave_office_name: string
  leave_period_start: string | null
  leave_period_end: string | null
  approved_days: number
  created_at: string
  updated_at: string
  // Joined data
  staff_profile?: {
    first_name: string
    last_name: string
    position: string
    department_id: string
  }
}

export function PaymentAdviceApprovalDashboard() {
  const [memos, setMemos] = useState<PaymentAdviceMemo[]>([])
  const [loading, setLoading] = useState(true)
  const [approvingId, setApprovingId] = useState<string | null>(null)
  const [selectedMemoId, setSelectedMemoId] = useState<string | null>(null)
  const [filterStatus, setFilterStatus] = useState<'all' | 'pending' | 'reviewed'>('pending')
  const [stats, setStats] = useState({ pending: 0, approved: 0, rejected: 0, totalMemos: 0 })
  const { toast } = useToast()

  useEffect(() => {
    fetchPaymentAdviceMemos()
  }, [filterStatus])

  const fetchPaymentAdviceMemos = async () => {
    setLoading(true)
    try {
      const supabase = createClient()
      const { data: { user } } = await supabase.auth.getUser()

      if (!user) {
        throw new Error('User not authenticated')
      }

      let query = supabase
        .from('leave_payment_memos')
        .select(`
          id,
          leave_plan_request_id,
          staff_id,
          staff_name,
          staff_number,
          memo_subject,
          memo_body,
          hr_leave_office_id,
          hr_leave_office_name,
          leave_period_start,
          leave_period_end,
          approved_days,
          created_at,
          updated_at
        `)

      // Apply status filter
      if (filterStatus === 'pending') {
        query = query.is('approved_at', null)
      } else if (filterStatus === 'reviewed') {
        query = query.not('approved_at', 'is', null)
      }

      const { data, error } = await query.order('created_at', { ascending: false })

      if (error) throw error

      const typedMemos = (data || []) as PaymentAdviceMemo[]
      setMemos(typedMemos)

      // Calculate stats
      const pending = typedMemos.filter((m) => !('approved_at' in m && m.approved_at)).length
      const all = typedMemos.length

      setStats({
        pending,
        approved: all - pending,
        rejected: 0,
        totalMemos: all,
      })
    } catch (error: any) {
      console.error('[v0] Error fetching memos:', error)
      toast({
        title: 'Error',
        description: error.message || 'Failed to load payment advice memos',
        variant: 'destructive',
      })
    } finally {
      setLoading(false)
    }
  }

  const handleApproveMemo = async (memoId: string) => {
    setApprovingId(memoId)
    try {
      const supabase = createClient()

      const { error } = await supabase
        .from('leave_payment_memos')
        .update({ approved_at: new Date().toISOString(), status: 'approved_by_executive' })
        .eq('id', memoId)

      if (error) throw error

      toast({
        title: 'Approved',
        description: 'Payment advice memo has been approved',
      })

      await fetchPaymentAdviceMemos()
    } catch (error: any) {
      console.error('[v0] Approve error:', error)
      toast({
        title: 'Error',
        description: error.message || 'Failed to approve memo',
        variant: 'destructive',
      })
    } finally {
      setApprovingId(null)
    }
  }

  const formatDate = (date: string | null) => {
    if (!date) return 'N/A'
    return new Date(date).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
    })
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="space-y-2">
        <h2 className="text-2xl font-bold text-slate-900">Payment Advice Approvals</h2>
        <p className="text-slate-600">
          Review and approve payment advice memos generated by HR Leave Office staff
        </p>
      </div>

      {/* Stats Cards */}
      <div className="grid gap-4 grid-cols-1 md:grid-cols-4">
        <Card>
          <CardHeader className="pb-3">
            <CardTitle className="text-sm font-medium text-slate-600">Total Memos</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-slate-900">{stats.totalMemos}</div>
            <p className="text-xs text-slate-500 mt-1">All payment advice memos</p>
          </CardContent>
        </Card>

        <Card className="border-yellow-200 bg-yellow-50">
          <CardHeader className="pb-3">
            <CardTitle className="text-sm font-medium text-yellow-900">Pending</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-yellow-900">{stats.pending}</div>
            <p className="text-xs text-yellow-700 mt-1">Awaiting your approval</p>
          </CardContent>
        </Card>

        <Card className="border-green-200 bg-green-50">
          <CardHeader className="pb-3">
            <CardTitle className="text-sm font-medium text-green-900">Approved</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-green-900">{stats.approved}</div>
            <p className="text-xs text-green-700 mt-1">Ready for finance</p>
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="pb-3">
            <CardTitle className="text-sm font-medium text-slate-600">Action Required</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-slate-900">{stats.pending}</div>
            <p className="text-xs text-slate-500 mt-1">Memos to review</p>
          </CardContent>
        </Card>
      </div>

      {/* Filter Tabs */}
      <div className="flex gap-2">
        <Button
          variant={filterStatus === 'pending' ? 'default' : 'outline'}
          onClick={() => setFilterStatus('pending')}
          className="gap-2"
        >
          <Clock className="h-4 w-4" />
          Pending
        </Button>
        <Button
          variant={filterStatus === 'reviewed' ? 'default' : 'outline'}
          onClick={() => setFilterStatus('reviewed')}
          className="gap-2"
        >
          <CheckCircle className="h-4 w-4" />
          Reviewed
        </Button>
        <Button
          variant={filterStatus === 'all' ? 'default' : 'outline'}
          onClick={() => setFilterStatus('all')}
          className="gap-2"
        >
          All Memos
        </Button>
      </div>

      {/* Loading State */}
      {loading && (
        <Card>
          <CardContent className="py-12">
            <div className="flex items-center justify-center gap-3">
              <Loader2 className="h-5 w-5 animate-spin" />
              <span>Loading payment advice memos...</span>
            </div>
          </CardContent>
        </Card>
      )}

      {/* Memos List */}
      {!loading && memos.length === 0 && (
        <Alert className="border-blue-200 bg-blue-50">
          <AlertCircle className="h-4 w-4 text-blue-600" />
          <AlertDescription className="text-blue-900">
            No payment advice memos found for the selected filter
          </AlertDescription>
        </Alert>
      )}

      {!loading && memos.length > 0 && (
        <div className="space-y-3">
          {memos.map((memo) => (
            <Card key={memo.id} className="hover:shadow-md transition-shadow">
              <CardHeader className="pb-3">
                <div className="flex items-start justify-between gap-4">
                  <div className="space-y-1 flex-1">
                    <div className="flex items-center gap-2">
                      <FileText className="h-4 w-4 text-slate-500" />
                      <h3 className="font-semibold text-slate-900">{memo.memo_subject}</h3>
                    </div>
                    <p className="text-sm text-slate-600">{memo.staff_name}</p>
                  </div>
                  <Badge variant="outline" className="whitespace-nowrap">
                    {memo.staff_number}
                  </Badge>
                </div>
              </CardHeader>

              <CardContent className="space-y-4">
                {/* Memo Details Grid */}
                <div className="grid gap-4 grid-cols-2 md:grid-cols-4">
                  <div>
                    <p className="text-xs text-slate-500 mb-1">Leave Period</p>
                    <p className="text-sm font-medium">
                      {formatDate(memo.leave_period_start)} to {formatDate(memo.leave_period_end)}
                    </p>
                  </div>
                  <div>
                    <p className="text-xs text-slate-500 mb-1">Approved Days</p>
                    <p className="text-sm font-medium text-emerald-600">{memo.approved_days} days</p>
                  </div>
                  <div>
                    <p className="text-xs text-slate-500 mb-1">Generated By</p>
                    <p className="text-sm font-medium">{memo.hr_leave_office_name}</p>
                  </div>
                  <div>
                    <p className="text-xs text-slate-500 mb-1">Created</p>
                    <p className="text-sm font-medium">{formatDate(memo.created_at)}</p>
                  </div>
                </div>

                {/* Action Buttons */}
                <div className="flex gap-2">
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={() => setSelectedMemoId(selectedMemoId === memo.id ? null : memo.id)}
                    className="gap-2"
                  >
                    <Eye className="h-4 w-4" />
                    {selectedMemoId === memo.id ? 'Hide' : 'View'} Details
                  </Button>
                  <Button
                    size="sm"
                    className="gap-2 bg-emerald-600 hover:bg-emerald-700"
                    onClick={() => handleApproveMemo(memo.id)}
                    disabled={approvingId === memo.id}
                  >
                    {approvingId === memo.id ? (
                      <>
                        <Loader2 className="h-4 w-4 animate-spin" />
                        Approving...
                      </>
                    ) : (
                      <>
                        <CheckCircle className="h-4 w-4" />
                        Approve
                      </>
                    )}
                  </Button>
                </div>

                {/* Expanded Details */}
                {selectedMemoId === memo.id && (
                  <div className="pt-4 border-t space-y-3">
                    <Alert className="bg-slate-50">
                      <AlertCircle className="h-4 w-4" />
                      <AlertDescription>
                        Please review the memo details below before approving
                      </AlertDescription>
                    </Alert>
                    <div className="bg-slate-50 p-3 rounded text-sm text-slate-700 max-h-48 overflow-y-auto font-mono text-xs">
                      {typeof memo.memo_body === 'string'
                        ? memo.memo_body
                        : JSON.stringify(memo.memo_body, null, 2)}
                    </div>
                  </div>
                )}
              </CardContent>
            </Card>
          ))}
        </div>
      )}
    </div>
  )
}
