"use client"

import { useState, useEffect } from "react"
import {
  FileText,
  Download,
  Calendar,
  Users,
  TrendingUp,
  CheckCircle,
  XCircle,
  Clock,
  RefreshCw,
  BarChart3,
  MapPin,
} from "lucide-react"
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"

interface ReportData {
  totalStaff: number
  staffOnLeave: number
  totalLeaveDays: number
  pendingRequests: number
  approvedRequests: number
  rejectedRequests: number
  averageLeaveUtilization: number
  leaveTypeBreakdown: Record<string, number>
  monthlyTrend: Array<{ month: string; count: number }>
}

interface SavedReport {
  id: string
  location_id: string
  location_name: string
  region_name: string
  report_month: number
  report_year: number
  report_period: string
  generated_by: string
  generated_by_name: string
  report_data: ReportData
  created_at: string
}

interface RegionalLeaveReportPanelProps {
  userId: string
  userName: string
  locationId: string | null
  locationName: string | null
  regionName: string | null
  isViewOnly?: boolean // For HR Leave Office viewing all reports
}

const MONTHS = [
  "January", "February", "March", "April", "May", "June",
  "July", "August", "September", "October", "November", "December"
]

export function RegionalLeaveReportPanel({
  userId,
  userName,
  locationId,
  locationName,
  regionName,
  isViewOnly = false,
}: RegionalLeaveReportPanelProps) {
  const [selectedMonth, setSelectedMonth] = useState(new Date().getMonth() + 1)
  const [selectedYear, setSelectedYear] = useState(new Date().getFullYear())
  const [generatedReport, setGeneratedReport] = useState<ReportData | null>(null)
  const [savedReports, setSavedReports] = useState<SavedReport[]>([])
  const [generating, setGenerating] = useState(false)
  const [loading, setLoading] = useState(true)
  const [viewingReport, setViewingReport] = useState<SavedReport | null>(null)

  // Load previously generated reports
  useEffect(() => {
    const loadReports = async () => {
      setLoading(true)
      try {
        const url = isViewOnly
          ? "/api/leave/regional-reports?viewAll=true"
          : `/api/leave/regional-reports?locationId=${locationId}`
        const res = await fetch(url)
        if (res.ok) {
          const data = await res.json()
          setSavedReports(data.reports || [])
        }
      } catch (err) {
        console.error("[v0] Failed to load reports:", err)
      } finally {
        setLoading(false)
      }
    }
    loadReports()
  }, [locationId, isViewOnly])

  // Generate report
  const handleGenerateReport = async () => {
    if (!locationId) return
    setGenerating(true)
    try {
      const res = await fetch("/api/leave/regional-reports", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          locationId,
          locationName,
          regionName,
          reportMonth: selectedMonth,
          reportYear: selectedYear,
          generatedBy: userId,
          generatedByName: userName,
        }),
      })
      if (res.ok) {
        const data = await res.json()
        setGeneratedReport(data.report?.report_data || null)
        if (data.report) {
          setSavedReports((prev) => [data.report, ...prev])
        }
      }
    } catch (err) {
      console.error("[v0] Failed to generate report:", err)
    } finally {
      setGenerating(false)
    }
  }

  // Export report as JSON (can be enhanced to PDF later)
  const handleExport = (report: ReportData) => {
    const blob = new Blob([JSON.stringify(report, null, 2)], { type: "application/json" })
    const url = URL.createObjectURL(blob)
    const a = document.createElement("a")
    a.href = url
    a.download = `leave-report-${selectedYear}-${String(selectedMonth).padStart(2, "0")}.json`
    a.click()
    URL.revokeObjectURL(url)
  }

  const displayReport = viewingReport?.report_data || generatedReport

  return (
    <div className="space-y-6">
      {/* Header */}
      <Card className="bg-gradient-to-br from-indigo-900/40 to-blue-800/20 border-indigo-700">
        <CardHeader>
          <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
            <div>
              <CardTitle className="text-white flex items-center gap-2">
                <FileText className="w-5 h-5 text-indigo-400" />
                {isViewOnly ? "Regional Leave Reports (All Regions)" : "Regional Monthly Leave Report"}
              </CardTitle>
              <CardDescription className="text-indigo-300">
                {isViewOnly
                  ? "View all reports generated by Regional HR Officers"
                  : `Generate and export leave reports for ${locationName || "your region"}`}
              </CardDescription>
            </div>
            {!isViewOnly && locationId && (
              <div className="flex items-center gap-2">
                <select
                  value={selectedMonth}
                  onChange={(e) => setSelectedMonth(Number(e.target.value))}
                  className="px-3 py-2 rounded-md bg-indigo-900/50 border border-indigo-600 text-white text-sm"
                >
                  {MONTHS.map((m, i) => (
                    <option key={m} value={i + 1}>{m}</option>
                  ))}
                </select>
                <select
                  value={selectedYear}
                  onChange={(e) => setSelectedYear(Number(e.target.value))}
                  className="px-3 py-2 rounded-md bg-indigo-900/50 border border-indigo-600 text-white text-sm"
                >
                  <option value={2024}>2024</option>
                  <option value={2025}>2025</option>
                  <option value={2026}>2026</option>
                </select>
                <Button
                  onClick={handleGenerateReport}
                  disabled={generating}
                  className="bg-indigo-600 hover:bg-indigo-700"
                >
                  {generating ? (
                    <>
                      <RefreshCw className="w-4 h-4 mr-1 animate-spin" />
                      Generating...
                    </>
                  ) : (
                    <>
                      <BarChart3 className="w-4 h-4 mr-1" />
                      Generate Report
                    </>
                  )}
                </Button>
              </div>
            )}
          </div>
        </CardHeader>
      </Card>

      {/* Generated Report Display */}
      {displayReport && (
        <Card className="bg-slate-800 border-slate-700">
          <CardHeader className="pb-2">
            <div className="flex items-center justify-between">
              <CardTitle className="text-white text-lg">
                {viewingReport ? (
                  <span className="flex items-center gap-2">
                    <MapPin className="w-4 h-4 text-indigo-400" />
                    {viewingReport.location_name} - {MONTHS[viewingReport.report_month - 1]} {viewingReport.report_year}
                  </span>
                ) : (
                  <span>{MONTHS[selectedMonth - 1]} {selectedYear} Report</span>
                )}
              </CardTitle>
              <div className="flex items-center gap-2">
                {viewingReport && (
                  <Button variant="outline" size="sm" onClick={() => setViewingReport(null)} className="border-slate-600">
                    Close
                  </Button>
                )}
                <Button
                  variant="outline"
                  size="sm"
                  onClick={() => handleExport(displayReport)}
                  className="border-slate-600"
                >
                  <Download className="w-4 h-4 mr-1" />
                  Export
                </Button>
              </div>
            </div>
            {viewingReport && (
              <p className="text-xs text-slate-400 mt-1">
                Generated by {viewingReport.generated_by_name} on {new Date(viewingReport.created_at).toLocaleDateString()}
              </p>
            )}
          </CardHeader>
          <CardContent className="space-y-4">
            {/* Key Metrics */}
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
              <div className="bg-slate-700/50 rounded-lg p-3">
                <div className="flex items-center gap-2 text-blue-400 mb-1">
                  <Users className="w-4 h-4" />
                  <span className="text-xs">Total Staff</span>
                </div>
                <p className="text-2xl font-bold text-white">{displayReport.totalStaff}</p>
              </div>
              <div className="bg-slate-700/50 rounded-lg p-3">
                <div className="flex items-center gap-2 text-amber-400 mb-1">
                  <Calendar className="w-4 h-4" />
                  <span className="text-xs">On Leave</span>
                </div>
                <p className="text-2xl font-bold text-white">{displayReport.staffOnLeave}</p>
              </div>
              <div className="bg-slate-700/50 rounded-lg p-3">
                <div className="flex items-center gap-2 text-green-400 mb-1">
                  <TrendingUp className="w-4 h-4" />
                  <span className="text-xs">Leave Days</span>
                </div>
                <p className="text-2xl font-bold text-white">{displayReport.totalLeaveDays}</p>
              </div>
              <div className="bg-slate-700/50 rounded-lg p-3">
                <div className="flex items-center gap-2 text-purple-400 mb-1">
                  <BarChart3 className="w-4 h-4" />
                  <span className="text-xs">Utilization</span>
                </div>
                <p className="text-2xl font-bold text-white">{displayReport.averageLeaveUtilization}%</p>
              </div>
            </div>

            {/* Request Status */}
            <div className="grid grid-cols-3 gap-3">
              <div className="bg-green-900/30 border border-green-700 rounded-lg p-3 text-center">
                <CheckCircle className="w-5 h-5 text-green-400 mx-auto mb-1" />
                <p className="text-xl font-bold text-white">{displayReport.approvedRequests}</p>
                <p className="text-xs text-green-300">Approved</p>
              </div>
              <div className="bg-amber-900/30 border border-amber-700 rounded-lg p-3 text-center">
                <Clock className="w-5 h-5 text-amber-400 mx-auto mb-1" />
                <p className="text-xl font-bold text-white">{displayReport.pendingRequests}</p>
                <p className="text-xs text-amber-300">Pending</p>
              </div>
              <div className="bg-red-900/30 border border-red-700 rounded-lg p-3 text-center">
                <XCircle className="w-5 h-5 text-red-400 mx-auto mb-1" />
                <p className="text-xl font-bold text-white">{displayReport.rejectedRequests}</p>
                <p className="text-xs text-red-300">Rejected</p>
              </div>
            </div>

            {/* Leave Type Breakdown */}
            <div className="bg-slate-700/30 rounded-lg p-4">
              <h4 className="text-white font-medium mb-3">Leave Type Breakdown</h4>
              <div className="flex flex-wrap gap-2">
                {Object.entries(displayReport.leaveTypeBreakdown).length > 0 ? (
                  Object.entries(displayReport.leaveTypeBreakdown).map(([type, count]) => (
                    <Badge key={type} variant="secondary" className="bg-slate-600 text-white">
                      {type.replace(/_/g, " ")}: {count}
                    </Badge>
                  ))
                ) : (
                  <p className="text-slate-400 text-sm">No leave requests in this period</p>
                )}
              </div>
            </div>

            {/* Monthly Trend */}
            <div className="bg-slate-700/30 rounded-lg p-4">
              <h4 className="text-white font-medium mb-3">6-Month Trend</h4>
              <div className="flex items-end justify-between gap-2 h-24">
                {displayReport.monthlyTrend.map((item, idx) => {
                  const maxCount = Math.max(...displayReport.monthlyTrend.map((t) => t.count), 1)
                  const height = (item.count / maxCount) * 100
                  return (
                    <div key={idx} className="flex-1 flex flex-col items-center gap-1">
                      <div
                        className="w-full bg-indigo-500 rounded-t"
                        style={{ height: `${Math.max(height, 5)}%` }}
                      />
                      <span className="text-xs text-slate-400">{item.month}</span>
                    </div>
                  )
                })}
              </div>
            </div>
          </CardContent>
        </Card>
      )}

      {/* Previously Generated Reports */}
      <Card className="bg-slate-800 border-slate-700">
        <CardHeader>
          <CardTitle className="text-white flex items-center gap-2">
            <FileText className="w-5 h-5 text-slate-400" />
            {isViewOnly ? "All Regional Reports" : "Report History"}
          </CardTitle>
        </CardHeader>
        <CardContent>
          {loading ? (
            <div className="py-8 text-center">
              <RefreshCw className="w-6 h-6 mx-auto text-slate-400 animate-spin mb-2" />
              <p className="text-slate-400">Loading reports...</p>
            </div>
          ) : savedReports.length === 0 ? (
            <div className="py-8 text-center">
              <FileText className="w-10 h-10 mx-auto text-slate-500 mb-2" />
              <p className="text-slate-400">No reports generated yet</p>
              {!isViewOnly && (
                <p className="text-slate-500 text-sm">Generate your first monthly report above</p>
              )}
            </div>
          ) : (
            <div className="space-y-2">
              {savedReports.map((report) => (
                <div
                  key={report.id}
                  className="flex items-center justify-between bg-slate-700/50 rounded-lg p-3 hover:bg-slate-700 transition-colors"
                >
                  <div className="flex items-center gap-3">
                    <div className="w-10 h-10 rounded-lg bg-indigo-900/50 flex items-center justify-center">
                      <FileText className="w-5 h-5 text-indigo-400" />
                    </div>
                    <div>
                      <p className="text-white font-medium">
                        {isViewOnly && <span className="text-indigo-400">{report.location_name} - </span>}
                        {MONTHS[report.report_month - 1]} {report.report_year}
                      </p>
                      <p className="text-xs text-slate-400">
                        {isViewOnly ? `By ${report.generated_by_name} - ` : ""}
                        {new Date(report.created_at).toLocaleDateString()}
                      </p>
                    </div>
                  </div>
                  <div className="flex items-center gap-2">
                    <Badge variant="secondary" className="bg-slate-600">
                      {report.report_data?.approvedRequests || 0} approved
                    </Badge>
                    <Button
                      variant="ghost"
                      size="sm"
                      onClick={() => setViewingReport(report)}
                      className="text-indigo-400 hover:text-indigo-300"
                    >
                      View
                    </Button>
                  </div>
                </div>
              ))}
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  )
}
