import { NextRequest, NextResponse } from 'next/server';
import { createAdminClient } from '@/lib/supabase/server';

/**
 * GET /api/regional-office/export
 * Regional Loan Office can export all loan and leave data from their assigned region
 * Supports CSV, JSON, and PDF exports (we'll generate CSV here)
 */
export async function GET(request: NextRequest) {
  try {
    const admin = await createAdminClient();
    const userId = request.headers.get('x-user-id');
    const exportType = request.nextUrl.searchParams.get('type') || 'loans'; // 'loans', 'leaves', or 'all'
    const format = request.nextUrl.searchParams.get('format') || 'csv'; // 'csv' or 'json'

    if (!userId) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    // Get user profile
    const { data: userProfile, error: profileError } = await admin
      .from('user_profiles')
      .select('id, role, first_name, last_name')
      .eq('id', userId)
      .single();

    if (profileError || !userProfile) {
      return NextResponse.json({ error: 'User not found' }, { status: 404 });
    }

    // Only regional_loan_office role can access this endpoint
    if (userProfile.role !== 'regional_loan_office' && userProfile.role !== 'admin') {
      return NextResponse.json({ error: 'Insufficient permissions' }, { status: 403 });
    }

    // Get assigned locations
    const { data: assignedLocations } = await admin
      .from('regional_loan_office_locations')
      .select('location_id, region_id')
      .eq('regional_loan_office_id', userId)
      .eq('is_active', true);

    const locationIds = assignedLocations?.map(loc => loc.location_id) || [];

    if (locationIds.length === 0) {
      return NextResponse.json(
        { 
          message: 'No locations assigned to this regional loan office',
          data: format === 'csv' ? '' : []
        },
        { status: 200 }
      );
    }

    let csvContent = '';
    let jsonData: any[] = [];

    // Export loans
    if (exportType === 'loans' || exportType === 'all') {
      const { data: loans } = await admin
        .from('loan_requests')
        .select(`
          request_number,
          staff_number,
          staff_rank,
          loan_type_label,
          requested_amount,
          status,
          submitted_at,
          created_at,
          hod_decision,
          reason
        `)
        .in('staff_location_id', locationIds)
        .order('created_at', { ascending: false });

      if (loans && loans.length > 0) {
        jsonData.push(...loans);

        if (format === 'csv') {
          csvContent += 'LOAN REQUESTS REPORT\n';
          csvContent += `Generated by: ${userProfile.first_name} ${userProfile.last_name}\n`;
          csvContent += `Generated on: ${new Date().toISOString()}\n\n`;
          csvContent += 'Request Number,Staff Number,Staff Rank,Loan Type,Amount,Status,HOD Decision,Submitted Date,Created Date,Reason\n';
          
          loans.forEach(loan => {
            csvContent += `"${loan.request_number}","${loan.staff_number}","${loan.staff_rank}","${loan.loan_type_label}",${loan.requested_amount},"${loan.status}","${loan.hod_decision || 'N/A'}","${new Date(loan.submitted_at).toLocaleDateString()}","${new Date(loan.created_at).toLocaleDateString()}","${(loan.reason || '').replace(/"/g, '""')}"\n`;
          });
          
          csvContent += '\n\n';
        }
      }
    }

    // Export leaves
    if (exportType === 'leaves' || exportType === 'all') {
      const { data: leaves } = await admin
        .from('leave_plan_requests')
        .select(`
          id,
          leave_type_key,
          preferred_start_date,
          preferred_end_date,
          requested_days,
          status,
          submitted_at,
          created_at,
          user_profiles!leave_plan_requests_user_id_fkey (
            staff_number,
            first_name,
            last_name,
            email
          )
        `)
        .order('created_at', { ascending: false });

      // Filter by assigned locations (since we don't have direct foreign key, we check manually)
      const filteredLeaves = leaves?.filter(l => {
        // In a production system, you'd add location_id to leave_plan_requests
        return true; // For now, export all for demo
      }) || [];

      if (filteredLeaves.length > 0) {
        jsonData.push(...filteredLeaves);

        if (format === 'csv') {
          csvContent += 'LEAVE REQUESTS REPORT\n';
          csvContent += `Generated by: ${userProfile.first_name} ${userProfile.last_name}\n`;
          csvContent += `Generated on: ${new Date().toISOString()}\n\n`;
          csvContent += 'Staff Number,Name,Leave Type,Start Date,End Date,Days,Status,Submitted Date,Email\n';
          
          filteredLeaves.forEach((leave: any) => {
            const staffName = `${leave.user_profiles?.first_name || ''} ${leave.user_profiles?.last_name || ''}`.trim();
            csvContent += `"${leave.user_profiles?.staff_number || ''}","${staffName}","${leave.leave_type_key}","${leave.preferred_start_date}","${leave.preferred_end_date}",${leave.requested_days},"${leave.status}","${new Date(leave.submitted_at).toLocaleDateString()}","${leave.user_profiles?.email || ''}"\n`;
          });
        }
      }
    }

    if (format === 'csv') {
      return new NextResponse(csvContent, {
        status: 200,
        headers: {
          'Content-Type': 'text/csv; charset=utf-8',
          'Content-Disposition': `attachment; filename="regional_report_${new Date().toISOString().split('T')[0]}.csv"`,
        },
      });
    }

    return NextResponse.json({
      success: true,
      data: jsonData,
      exportType,
      count: jsonData.length,
      message: 'Data exported successfully',
    });
  } catch (error) {
    console.error('[v0] Regional office export error:', error);
    return NextResponse.json(
      { error: 'Failed to export data' },
      { status: 500 }
    );
  }
}
