"use client"

import { useEffect, useState } from "react"
import { Download, Check, X, UserPlus } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { toast } from "@/hooks/use-toast"

export function NonRegionalRequisitionDashboard({ role }: { role: string }) {
  const [requests, setRequests] = useState<any[]>([])
  const [drivers, setDrivers] = useState<any[]>([])
  const [busy, setBusy] = useState<string | null>(null)
  async function load() { const response = await fetch("/api/transport/nonregional"); const body = await response.json(); setRequests(body.requests ?? []) }
  useEffect(() => { load() }, [])
  async function decide(id: string, decision: string, extra: Record<string, unknown> = {}) { setBusy(id); const response = await fetch("/api/transport/nonregional", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id, decision, ...extra }) }); setBusy(null); if (!response.ok) { const body = await response.json().catch(() => null); toast({ title: "Action failed", description: body?.error ?? "Please try again.", variant: "destructive" }); return } toast({ title: "Requisition updated" }); load() }
  function download(request: any) { const lines = [`QUALITY CONTROL COMPANY LIMITED`, `REQUISITION FOR TRANSPORT`, ``, `Date: ${request.requisition_date}`, `Requester’s Department: ${request.department}`, `Location: ${request.location}`, `From: ${request.origin}`, `To: ${request.destination}`, `Purpose: ${request.purpose}`, `Date and Time Required: ${request.required_at}`, `Date and Time of Return: ${request.return_at ?? "—"}`, `Person(s) Requiring Transport: ${request.persons_requiring_transport}`, `Head of Department Authorization: ${request.hod_authorization}`, ``, `TRANSPORT USE ONLY`, `Recommended Vehicle: ${request.recommended_vehicle ?? "—"}`, `Recommended Driver: ${request.driver ? `${request.driver.first_name ?? ""} ${request.driver.last_name ?? ""}` : "—"}`, `Date: ${request.transport_use_date ?? "—"}`].join("\n"); const url = URL.createObjectURL(new Blob([lines], { type: "text/plain" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `transport-requisition-${request.id}.txt`; anchor.click(); URL.revokeObjectURL(url) }
  return <main className="grid gap-6"><header><p className="text-sm font-medium text-primary">Non-regional transport</p><h1 className="text-3xl font-semibold tracking-tight">Transport requisitions</h1><p className="mt-1 text-muted-foreground">Head Office, Awutu Stores, and Nsawam Archives.</p></header>{role === "department_head" && <a className="inline-flex w-fit rounded-md bg-primary px-4 py-2 text-primary-foreground" href="/dashboard/transport/nonregional/new">New requisition</a>}<div className="grid gap-4">{requests.map((request) => <Card key={request.id}><CardHeader><div className="flex flex-wrap items-center justify-between gap-3"><CardTitle>{request.department} — {request.location}</CardTitle><span className="rounded-full bg-muted px-3 py-1 text-xs font-medium">{request.status}</span></div></CardHeader><CardContent className="grid gap-4"><div className="grid gap-2 text-sm md:grid-cols-3"><p><strong>From:</strong> {request.origin}</p><p><strong>To:</strong> {request.destination}</p><p><strong>Required:</strong> {request.required_at}</p></div><p className="text-sm leading-6">{request.purpose}</p><div className="flex flex-wrap gap-2">{role === "managing_director" && request.md_decision === "pending" && <><Button onClick={() => decide(request.id, "approve")} disabled={busy === request.id}><Check data-icon="inline-start" /> Approve</Button><Button variant="destructive" onClick={() => decide(request.id, "reject")} disabled={busy === request.id}><X data-icon="inline-start" /> Reject</Button></>}{role === "transport_manager" && request.md_decision === "approved" && <Button variant="outline" onClick={() => { const driverId = window.prompt("Enter assigned driver user ID"); if (driverId) decide(request.id, "assign_driver", { driverId, recommendedVehicle: window.prompt("Recommended vehicle") ?? "", transportUseDate: new Date().toISOString().slice(0, 10) }) }}><UserPlus data-icon="inline-start" /> Assign location driver</Button>}{request.md_decision === "approved" && <Button variant="outline" onClick={() => download(request)}><Download data-icon="inline-start" /> Download approved request</Button>}</div></CardContent></Card>)}</div></main>
}
