"use client"

import { CheckCircle2, FileSignature, ShieldCheck, Clock3, ArrowRight, CarFront, Route, Bus } from "lucide-react"
import Link from "next/link"
import type { ReactNode } from "react"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"

export function TransportApprovalDashboard({ role, pendingCount, totalCount, regionalPendingCount = pendingCount, nonRegionalPendingCount = 0 }: { role: "managing_director" | "hr_executive"; pendingCount: number; totalCount: number; regionalPendingCount?: number; nonRegionalPendingCount?: number }) {
  const isMd = role === "managing_director"
  const title = isMd ? "Managing Director control desk" : "HR Executive signing desk"
  const description = isMd ? "Review endorsed regional transport requests, preview the formal memo, and approve the next handoff." : "Prepare the response memo, preview the final document, sign with your profile signature, and send it to HR Records."
  if (!isMd) return <section aria-labelledby="approval-dashboard-title" className="grid gap-4 lg:grid-cols-[1fr_auto]">
    <Card className="overflow-hidden border-primary/20 bg-primary/[0.03]"><CardHeader className="border-b border-primary/10 bg-background/70"><div className="flex items-start gap-3"><div className="flex size-10 items-center justify-center rounded-xl bg-primary/10 text-primary"><FileSignature /></div><div><Badge variant="secondary">Priority workspace</Badge><CardTitle id="approval-dashboard-title" className="mt-2 text-xl">{title}</CardTitle><p className="mt-1 max-w-2xl text-sm leading-6 text-muted-foreground">{description}</p></div></div></CardHeader><CardContent className="flex flex-wrap gap-3 p-5 text-sm"><div className="flex items-center gap-2 rounded-lg border bg-background px-3 py-2"><Clock3 className="text-primary" /> <span><strong>{pendingCount}</strong> waiting for your action</span></div><div className="flex items-center gap-2 rounded-lg border bg-background px-3 py-2"><CheckCircle2 className="text-primary" /> <span><strong>{totalCount}</strong> requests in your workspace</span></div></CardContent></Card>
    <Card className="lg:min-w-64"><CardHeader><CardTitle className="text-base">Required sequence</CardTitle></CardHeader><CardContent className="flex flex-col gap-3 text-sm text-muted-foreground"><p>1. Open request</p><p>2. Check details</p><p>3. Edit, save, then sign</p></CardContent></Card>
  </section>

  return <section aria-labelledby="approval-dashboard-title" className="grid gap-5">
    <Card className="overflow-hidden border-primary/25 bg-gradient-to-br from-primary/[0.12] via-card to-card shadow-sm">
      <CardHeader className="border-b border-primary/10 p-6"><div className="flex flex-col gap-5 md:flex-row md:items-center md:justify-between"><div className="flex items-start gap-4"><div className="flex size-14 shrink-0 items-center justify-center rounded-2xl bg-primary text-primary-foreground shadow-sm"><ShieldCheck className="size-7" /></div><div><Badge variant="secondary">Executive control centre</Badge><CardTitle id="approval-dashboard-title" className="mt-2 text-2xl">Managing Director approval desk</CardTitle><p className="mt-1 max-w-2xl text-sm leading-6 text-muted-foreground">One view for every request that has reached your decision stage. HOD-pending non-regional requests stay out of this queue.</p></div></div><div className="flex flex-wrap gap-2"><ButtonLink href="/dashboard/transport/requests" icon={<ShieldCheck className="size-4" />} badge={pendingCount}>Open approval desk</ButtonLink><ButtonLink href="/dashboard/transport/fleet" icon={<CarFront className="size-4" />}>View nationwide fleet</ButtonLink></div></div></CardHeader>
      <CardContent className="grid gap-3 p-5 sm:grid-cols-2 xl:grid-cols-4"><ExecutiveMetric label="Needs your decision" value={pendingCount} note="All approval queues" icon={<Clock3 className="size-5" />} urgent /><ExecutiveMetric label="Regional approvals" value={regionalPendingCount} note="Regional transport" icon={<Bus className="size-5" />} /><ExecutiveMetric label="Non-regional approvals" value={nonRegionalPendingCount} note="HOD-cleared requests" icon={<Route className="size-5" />} /><ExecutiveMetric label="Workspace register" value={totalCount} note="Requests visible to you" icon={<CheckCircle2 className="size-5" />} /></CardContent>
    </Card>
    <div className="grid gap-3 sm:grid-cols-3" aria-label="Managing Director work areas"><ButtonLink href="/dashboard/transport/requests" icon={<Bus className="size-4" />} badge={regionalPendingCount}>Regional approval queue</ButtonLink><ButtonLink href="/dashboard/transport/nonregional" icon={<Route className="size-4" />} badge={nonRegionalPendingCount}>Non-regional approval queue</ButtonLink><ButtonLink href="/dashboard/transport/fleet" icon={<CarFront className="size-4" />}>Fleet inventory nationwide</ButtonLink></div>
  </section>
}

function ExecutiveMetric({ label, value, note, icon, urgent = false }: { label: string; value: number; note: string; icon: ReactNode; urgent?: boolean }) { return <div className={`flex items-center gap-3 rounded-xl border p-4 ${urgent ? "border-amber-500/30 bg-amber-500/[0.08]" : "bg-background/75"}`}><div className={`flex size-10 items-center justify-center rounded-xl ${urgent ? "bg-amber-500/15 text-amber-700" : "bg-primary/10 text-primary"}`}>{icon}</div><div><p className="text-2xl font-semibold tracking-tight">{value}</p><p className="text-xs font-medium">{label}</p><p className="text-[11px] text-muted-foreground">{note}</p></div></div> }

function ButtonLink({ href, children, icon, badge }: { href: string; children: ReactNode; icon: ReactNode; badge?: number }) { return <Link href={href} className="flex items-center justify-between rounded-xl border bg-card px-4 py-3 text-sm font-medium shadow-sm transition-colors hover:border-primary/50 hover:bg-primary/[0.04]"><span className="flex items-center gap-2">{icon}{children}</span><span className="flex items-center gap-2">{badge !== undefined && <Badge variant="secondary">{badge}</Badge>}<ArrowRight className="size-4 text-muted-foreground" /></span></Link> }
